### ISSUE TITLE
Make speed upgrade into health

### ISSUE THREAD

**Issue by EmilLinnebjerg** [EmilLinnebjerg/HeroesOfWar#4]

**Comment by kafudesign** [comment]
ideas for upgrades

Knight - get more damage, restore health
Archer - more attack speed, higher attack range
Mage - reset magic decay, faster shields

**Comment by abirsrh** [comment]
Nico's idea is good, except I am not entirely sure about the mage's shields. Let's see what Emil comes up with.

**Comment by EmilLinnebjerg** [comment]
I belive it will be quit simply to change code wise. The hard part is displaying this to the user in a good way so that they understand what a upgrade does. Along with this we probebly need ui elements.
